ktor:
  deployment:
    port: 8080
  application:
    modules:
      - pl.slaszu.HttpKt.configureHttp
      - pl.slaszu.SerializationKt.configureSerialization
      - pl.slaszu.KoinKt.configureKoin
      - pl.slaszu.RoutingKt.configureRouting

database:
  url: ${DB_URL?:jdbc:mysql://localhost:3309/gpw-db}
  user: ${DB_USER?:gpw}
  password: ${DB_PASSWORD?:gpw-password-213!}