[versions]
exposed = "1.3.0"
mysql = "26.7.0"
hikaricp = "7.1.0"
koin = "4.2.2"
kotlin = "2.4.0"
logback = "1.5.35"
kotlinx-serialization = "1.6.3"
kotlinx-datetime = "0.8.0"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
mysql-connector = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }


koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-loggerSlf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
